# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170101_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_planets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='position_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='position_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='starName',
            field=models.CharField(blank=True, default='newSTAR', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
