# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='starColor',
            field=models.CharField(blank=True, default='white', max_length=30),
        ),
    ]
