# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20161217_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='kind',
            field=models.CharField(default='environment', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.CharField(default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='totalmembers',
            field=models.IntegerField(default=0),
        ),
    ]
