# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_totalmembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='goal',
            field=models.CharField(default='123', max_length=20),
        ),
    ]
