# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20161229_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='totalmembers',
            field=models.CharField(default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='goal',
            field=models.CharField(default='public', max_length=20),
        ),
    ]
