# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('posts', '0010_auto_20161229_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attendant',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='totalmembers',
            field=models.IntegerField(default=0),
        ),
    ]
