# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 03:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20161230_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attendant',
            field=models.ManyToManyField(related_name='post_atteddant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
