# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attendant',
            field=models.ManyToManyField(related_name='post_attendant', to=settings.AUTH_USER_MODEL),
        ),
    ]
