# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20170102_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
